# Generated by Django 3.0.6 on 2020-05-30 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(default='url(https://i.ibb.co/R4vKybs/download.jpg)', upload_to='posts'),
        ),
    ]
